workflows:
  ios-unsigned:
    name: Build 3105 IPA
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Build without scheme
        script: |
          xcodebuild -project ThreeOneOSFive.xcodeproj -sdk iphoneos -configuration Release -derivedDataPath build CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" -arch arm64 build
          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/*.app Payload/
          ls -lh Payload/
          zip -r ThreeOneOSFive-unsigned.ipa Payload
    artifacts:
      - ./*.ipa
