name: Build IPA FILE
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build IPA as File
        run: |
          xcodebuild -project ThreeOneOSFive.xcodeproj -scheme ThreeOneOSFive -sdk iphoneos -configuration Release CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY="" -derivedDataPath build
          mkdir Payload
          cp -r build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r OGIOS-file.ipa Payload
      - uses: actions/upload-artifact@v4
        with:
          name: OGIOS-file-ipa
          path: OGIOS-file.ipa
